services:
  web:
    build:
      context: ./notes-app-backend
      dockerfile: Dockerfile
    container_name: notes-app-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./notes-app-backend/:/usr/src/notes-app-backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: notes-app-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=flare
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notes_db
    ports:
      - 5433:5432

volumes:
  postgres_data: